# Generated by Django 3.2.3 on 2021-05-23 14:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UUIDData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_uuid", models.UUIDField(default=uuid.uuid4)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "UUIDData",
                "verbose_name_plural": "UUIDData",
                "ordering": ["-created_date"],
            },
        ),
    ]
